# Generated by Django 4.1.7 on 2023-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryduo',
            name='ifftorlik',
            field=models.TextField(help_text='Please write prayer for Ifftorlik', unique=True, verbose_name='Ifftorlik'),
        ),
        migrations.AlterField(
            model_name='categoryduo',
            name='saharlik',
            field=models.TextField(help_text='Please write prayer for Saharlik', unique=True, verbose_name='Saharlik'),
        ),
    ]
