# Generated by Django 4.1.4 on 2023-03-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categoryduo_ifftorlik_and_more'),
    ]

    operations = [
    ]
