# Generated by Django 4.1.4 on 2023-03-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20230321_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryregion',
            name='asr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='asr'),
        ),
        migrations.AddField(
            model_name='categoryregion',
            name='bomdod',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='bomdod'),
        ),
        migrations.AddField(
            model_name='categoryregion',
            name='peshin',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='peshin'),
        ),
        migrations.AddField(
            model_name='categoryregion',
            name='quyosh',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='quyosh'),
        ),
        migrations.AddField(
            model_name='categoryregion',
            name='shom',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='shom'),
        ),
        migrations.AddField(
            model_name='categoryregion',
            name='xufton',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='xufton'),
        ),
    ]
