# Generated by Django 4.1.7 on 2023-03-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_ramadan_ifftorlik_prayer_ramadan_saharlik_prayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='namazuser',
            options={'verbose_name': 'Namaz User', 'verbose_name_plural': 'Namaz Users'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='ramadan',
            options={'verbose_name': 'Ramadan', 'verbose_name_plural': 'Ramadan'},
        ),
    ]
