# Generated by Django 4.1.7 on 2023-03-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_namazuser_region_alter_namazuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namazuser',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='User ID'),
        ),
    ]
